name: "build"
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: datakurre
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: >
        nix build .#docs
        cp -aL result build;
        chmod a+w -R build;
        rm result
    - run: nix-shell shell.nix --run "echo OK"
    - run: nix-shell default.nix --run "echo OK"
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: build
        single-commit: true
