name: "build"
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: datakurre
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: >
        nix build .#docs;
        cp -aL result build;
        chmod a+w -R build;
        touch build/.nojekyll
        rm result
    - uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: gh-pages
        folder: build
        single-commit: true
